### PR TITLE
restrict signature of order to NumField

### LINKED ISSUE #2071: Stack overflow at creation of a p-adic order
```
julia> E,a = cyclotomic_field(5)
(Cyclotomic field of order 5, z_5)

julia> OE = maximal_order(E)
Maximal order
  of number field with defining polynomial _$^4 + _$^3 + _$^2 + _$ + 1
    over rational field
with Z-basis [1, z_5, z_5^2, z_5^3]

julia> P = 2*OE; is_prime(P)
true

julia> E_P, i_P = completion(E,P)
(Eisenstein extension with defining polynomial x + 2^1 + 2^2 + 2^3 + 2^4 + 2^5 + 2^6 + 2^7 + 2^8 + 2^9 + 2^10 + 2^11 + 2^12 + 2^13 + 2^14 + 2^15 + 2^16 + 2^17 + 2^18 + 2^19 + 2^20 + 2^21 + 2^22 + 2^23 + 2^24 + 2^25 + 2^26 + 2^27 + 2^28 + 2^29 + 2^30 + 2^31 + 2^32 + 2^33 + 2^34 + 2^35 + 2^36 + 2^37 + 2^38 + 2^39 + 2^40 + 2^41 + 2^42 + 2^43 + 2^44 + 2^45 + 2^46 + 2^47 + 2^48 + 2^49 + 2^50 + 2^51 + 2^52 + 2^53 + 2^54 + 2^55 + 2^56 + 2^57 + 2^58 + 2^59 + 2^60 + 2^61 + 2^62 + 2^63 + O(2^64) over unramified extension of 2-adic numbers of degree 4, Map: E -> Eisenstein extension with defining polynomial x + 2^1 + 2^2 + 2^3 + 2^4 + 2^5 + 2^6 + 2^7 + 2^8 + 2^9 + 2^10 + 2^11 + 2^12 + 2^13 + 2^14 + 2^15 + 2^16 + 2^17 + 2^18 + 2^19 + 2^20 + 2^21 + 2^22 + 2^23 + 2^24 + 2^25 + 2^26 + 2^27 + 2^28 + 2^29 + 2^30 + 2^31 + 2^32 + 2^33 + 2^34 + 2^35 + 2^36 + 2^37 + 2^38 + 2^39 + 2^40 + 2^41 + 2^42 + 2^43 + 2^44 + 2^45 + 2^46 + 2^47 + 2^48 + 2^49 + 2^50 + 2^51 + 2^52 + 2^53 + 2^54 + 2^55 + 2^56 + 2^57 + 2^58 + 2^59 + 2^60 + 2^61 + 2^62 + 2^63 + O(2^64) over QQ_2^4)

julia> order(E_P,[i_P(a)])
Warning: detected a stack overflow; program state may be corrupted, so further execution might be unreliable.
Warning: detected a stack overflow; program state may be corrupted, so further execution might be unreliable.
ERROR: StackOverflowError:
Stacktrace:
 [1] order(K::Hecke.LocalField{…}, a::Vector{…}; check::Bool, isbasis::Bool, cached::Bool)
   @ Hecke ~/.julia/dev/Hecke/src/NumFieldOrd/NfOrd/NfOrd.jl:768
 [2] order(K::Hecke.LocalField{…}, a::Vector{…}; check::Bool, isbasis::Bool, cached::Bool) (repeats 18677 times)
   @ Hecke ~/.julia/dev/Hecke/src/NumFieldOrd/NfOrd/NfOrd.jl:774
 [3] order(K::Hecke.LocalField{QadicFieldElem, Hecke.EisensteinLocalField}, a::Vector{Hecke.LocalFieldElem{…}})
   @ Hecke ~/.julia/dev/Hecke/src/NumFieldOrd/NfOrd/NfOrd.jl:765
 [4] top-level scope
   @ REPL[7]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by simonbrandhorst**
Fixes #2071.

### CODE REVIEW

File: src/NumFieldOrd/NfOrd/NfOrd.jl [hunk 1]
```diff
@@ -774,6 +774,7 @@ function order(K, a::Vector; check::Bool = true, isbasis::Bool = false,
   return order(K, b, check = check, cached = cached, isbasis = isbasis)
 end
 
+
```
Comment (simonbrandhorst) [inline src/NumFieldOrd/NfOrd/NfOrd.jl]:
```suggestion
```
