### PR TITLE
add irreducible_components for Z-lattices, fix root_lattice_recognition

### LINKED ISSUE #920: Issue with decomposition into sum of ADE-type  lattices
The computation of the ADE-type connected components of a root lattice might create root-sublattices, aka connected components, which are themselves not necessarily indecomposable. In the following example:

```
julia> rsL
Quadratic lattice of rank 19 and degree 20 over the rationals

julia> gram_matrix(rsL)
[-2    1   -1   -1    0    0    0    0    1    0    0    0    0    0    0    0    0    0   -1]
[ 1   -2    1    1    0    0    0    0   -1    0    0    0    0    0    0    0    0    0    0]
[-1    1   -2    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0]
[-1    1    0   -2    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0]
[ 0    0    0    0   -2    1    1    0    1    0    0    0    0    0    0    0    0    1    0]
[ 0    0    0    0    1   -2   -1    0    0    0    0    0    0    0    0    0    0   -1    0]
[ 0    0    0    0    1   -1   -2    0   -1    0    0    0    0    0    0    0    0    0    0]
[ 0    0    0    0    0    0    0   -2    0    0    0    0    0    0    0    0    0    0    0]
[ 1   -1    1    1    1    0   -1    0   -4    0    0    0    0    0    0    0    0    1    0]
[ 0    0    0    0    0    0    0    0    0   -2   -1    1   -1   -1   -1   -1   -1    0    0]
[ 0    0    0    0    0    0    0    0    0   -1   -2    1   -1    0   -1   -1   -1    0    0]
[ 0    0    0    0    0    0    0    0    0    1    1   -2    0    0    0    1    1    0    0]
[ 0    0    0    0    0    0    0    0    0   -1   -1    0   -2   -1   -1   -1   -1    0    0]
[ 0    0    0    0    0    0    0    0    0   -1    0    0   -1   -2    0    0    0    0    0]
[ 0    0    0    0    0    0    0    0    0   -1   -1    0   -1    0   -2   -1   -1    0    0]
[ 0    0    0    0    0    0    0    0    0   -1   -1    1   -1    0   -1   -2   -1    0    0]
[ 0    0    0    0    0    0    0    0    0   -1   -1    1   -1    0   -1   -1   -2    0    0]
[ 0    0    0    0    1   -1    0    0    1    0    0    0    0    0    0    0    0   -2    0]
[-1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   -2]
```
we have an error while asking `root_lattice_recognition` because of `_connected_components`. Indeed: 

```
julia> Hecke._connected_components(rsL)
ERROR: not a definite root lattice
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] ADE_type(G::fmpq_mat)
   @ Hecke ~/.julia/dev/Hecke/src/QuadForm/Quad/ZLattices.jl:1611
 [3] _connected_components(L::ZLat)
   @ Hecke ~/.julia/dev/Hecke/src/QuadForm/Quad/ZLattices.jl:1512
 [4] top-level scope
   @ REPL[70]:1
```

This is due to the fact that the first connected components computed by `_connected_components(rsL)` is actually $D_4 \oplus D_6$. So I understand where the problem is coming from, but I don't see how to fix it.

To reproduce, this is how to get `rsL`

```
B = matrix(FlintQQ, 19, 20 ,[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]);
G = matrix(FlintQQ, 20, 20 ,[-2, 0, 1, -1, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -4, 0, 0, 0, -1, -1, -2, -2, -2, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 0, -2, 1, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 0, -2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, -2, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 0, 0, 0, 0, -2, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 0, 0, 0, -1, -1, -4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -2, -1, 1, 1, 0, -1, -1, 0, -4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, -1, 1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -2, 1, -1, 0, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, -2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, -2, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, -1, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, -1, 0, -2, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 1, -1, 0, -1, -2, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 1, -1, 0, -1, -1, -2, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2]);
rsL = Zlattice(B, gram = G);
```

Note that, and this is where it is even more strange, if we avoid the obvious orthogonal block of the gram matrix of `rsL` (rows 10 to 17), one can compute the `root_lattice_recognition` of the remaining block.

```
julia> lattice_in_same_ambient_space(rsL, basis_matrix(rsL)[[1,2,3,4,5,6,7,8,9,18,19], :])
Quadratic lattice of rank 11 and degree 20 over the rationals

julia> root_lattice_recognition(ans)
([(:D, 6), (:D, 4), (:A, 1)], ZLat[Quadratic lattice of rank 6 and degree 20 over the rationals, Quadratic lattice of rank 4 and degree 20 over the rationals, Quadratic lattice of rank 1 and degree 20 over the rationals])
```

@simonbrandhorst this is the non-working example I mentioned to you

### PR DESCRIPTION
**Pull request by simonbrandhorst**
Fixes #920

### CODE REVIEW

File: src/QuadForm/Quad/ZLattices.jl [hunk 1]
```diff
@@ -1479,17 +1479,77 @@ julia> R = root_lattice_recognition(L)
...
+@doc Markdown.doc"""
+    irreducible_components(L::ZLat)
+
+Return the irreducible components ``L_i`` of the positive definite lattice ``L``.
+
+This yields a maximal orthogonal splitting of `L` as
+```math
+L = \bigoplus_i L_i.
+```
+The upper bound is used for the short vector computation.
```
Comment (thofma) [inline src/QuadForm/Quad/ZLattices.jl:1495]: Hm, which upper bound?

Comment (simonbrandhorst) [reply src/QuadForm/Quad/ZLattices.jl:1495]: Right, I removed it from the interface. Thx.

Comment (simonbrandhorst) [inline src/QuadForm/Quad/ZLattices.jl:1495]:
```suggestion
```
